config/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls', namespace='home')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
] + debug_toolbar_urls()

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product/<int:pk>/', views.ProductDetail.as_view(), name='product'),
    path('comment/<int:pk>/', views.CommentCreateView.as_view(), name='comment'),
]

orders/urls.py
from django.urls import path
from . import views



app_name = 'orders'

urlpatterns = [
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('add/<int:product_id>/', views.AddToCartView.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', views.RemoveFromCartView.as_view(), name='cart_remove'),
    path('clear/', views.ClearCartView.as_view(), name='cart_clear')
]

shop/models.py
from django.db import models

shop/forms.py
from django import forms


class AddToCartProdcutForm(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 30)]

    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)
    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput, initial=True)

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View, generic
from .cart import Cart
from .forms import AddToCartProdcutForm
from home.models import Product
from django.http import HttpResponseNotAllowed, HttpResponse

class CartView(View):
    def get(self, request):
        cart = Cart(request)
        for item in cart:
            item['quantity_update_form'] = AddToCartProdcutForm(initial={
                'quantity': item['quantity'],
                'inplace': True,
            })
        return render(request, 'shop/cart.html', {'cart': cart})
        


class AddToCartView(View):
    def get(self, request, *args, **kwargs):
        response = render(request, '405.html')
        return HttpResponseNotAllowed(['POST'], response)

    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = AddToCartProdcutForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            quantity = cd['quantity']
            cart.add(product=product, quantity=quantity, replace_current_quantity=cd['inplace'])
        return redirect('shop:cart')
    

class RemoveFromCartView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, pk=product_id)
        cart.remove(product=product)
        return redirect('shop:cart')
    
class ClearCartView(View):
    def get(self, request):
        cart = Cart(request)
        cart.clear()
        return redirect('home:home')

shop/templates/shop/cart.html
{% extends "_base.html" %}

{% load humanize %}
{% load persian_numbers %}
<body dir="rtl">
    {% block content %}
    
    <!-- Preloader Start -->
    <div class="ShoppingYar-preloader active">
        <div class="ShoppingYar-preloader-inner h-100 d-flex align-items-center justify-content-center">
            <div class="ShoppingYar-child ShoppingYar-bounce1"></div>
            <div class="ShoppingYar-child ShoppingYar-bounce2"></div>
            <div class="ShoppingYar-child zuka-bounce3"></div>
        </div>
    </div>
    <!-- Preloader End -->

    <!-- Main Wrapper Start -->
    <div class="wrapper">

        <!-- Breadcrumb area Start -->
        <div class="breadcrumb-area bg-color ptb--90" data-bg-color="#f6f6f6">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex justify-content-between align-items-center flex-sm-row flex-column">
                            <h1 class="page-title">سبد خرید</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Breadcrumb area End -->

        <!-- Main Content Wrapper Start -->
        <div class="main-content-wrapper">
            <div class="page-content-inner ptb--80">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 mb-md--50">
                                <div class="row no-gutters">
                                    <div class="col-12">
                                        <div class="table-content table-responsive">
                                            <table class="table text-center">
                                                <thead>
                                                    <tr>
                                                        <th>&nbsp;</th>
                                                        <th>عکس محصول</th>
                                                        <th>نام محصول</th>
                                                        <th>قیمت</th>
                                                        <th>مقدار</th>
                                                        <th>مجموع</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for item in cart %}
                                                    
                                                    <tr>
                                                        <td class="product-remove text-left"><a href="{% url "shop:cart_remove" item.product_obj.id %}"><i class="flaticon flaticon-cross"></i></a></td>
                                                        <td class="product-thumbnail text-left">
                                                            <img src="{{ item.product_obj.picture.url }}">
                                                        </td>
                                                        <td class="product-name">
                                                            <h3>
                                                                <a href="{{ item.product_obj.get_absolute_url }}">{{ item.product_obj.title }}</a>
                                                            </h3>
                                                        </td>
                                                        <td class="product-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{ item.product_obj.price|intcomma|translate_number }}</span>
                                                            </span>
                                                        </td>
                                                        <td class="product-quantity">
                                                            <form class='d-flex' action="{% url "shop:cart_add" item.product_obj.id %}" method="POST">
                                                                {% csrf_token %}
                                                                <div class="quantity">
                                                                    <input type="number" class="quantity-input" name="quantity" id="qty-1" value="{{ item.quantity }}" min="1">
                                                                </div>
                                                                {{ item.quantity_update_form.inplace }}
                                                                {% comment %} <input type="hidden" name="inplace" value="True"> {% endcomment %}
                                                                <button class='btn' type="submit"><i class='fa fa-refresh'></i></button>
                                                            </form>
                                                        </td>
                                                        <td class="product-total-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{ item.total_price|intcomma|translate_number }}</span>
                                                            </span>
                                                        </td>
                                                    </tr>
                                                    {% endfor %}

                                                </tbody>
                                            </table>
                                        </div>  
                                    </div>
                                </div>
                                <div class="row no-gutters border-top pt--20 mt--20">
                                    <div class="col-sm-6 text-sm-right">
                                        <button type="submit" class="cart-form__btn"><a href ='{% url "shop:cart_clear" %}'>خالی کردن سبد خرید</a></button>
                                    </div>
                                </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="cart-collaterals">
                                <div class="cart-totals">
                                    <h5 class="font-size-14 font-bold mb--15">مجموع</h5>
                                    <div class="cart-calculator">
                                        <div class="cart-calculator__item">
                                        </div>
                                        <div class="cart-calculator__item order-total">
                                            <div class="cart-calculator__item--head">
                                                <span>جمع کل</span>
                                            </div>
                                            <div class="cart-calculator__item--value">
                                                <span class="product-price-wrapper">
                                                    <span class="money">تومان {{ cart.get_total_price|intcomma|translate_number }}</span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <a href="{% url "orders:checkout" %}" class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2">
                                    ثبت سفارش
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Main Content Wrapper Start -->


        <!-- Search form Popup Start -->
        <div class="searchform__popup" id="searchForm">
            <a href="#" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
            <div class="searchform__body">
                <p>Start typing and press Enter to search</p>
                <form class="searchform">
                    <input type="text" name="popup-search" id="popup-search" class="searchform__input" placeholder="Search Entire Store...">
                    <button type="submit" class="searchform__submit"><i class="flaticon flaticon-magnifying-glass-icon"></i></button>
                </form>
            </div>
        </div>
        <!-- Search form Popup End -->
        <!-- Global Overlay Start -->
        <div class="ShoppingYar-global-overlay"></div>
        <!-- Global Overlay End -->

    </div>
    <!-- Main Wrapper End -->
 

    <!-- ************************* JS Files ************************* -->

    <!-- jQuery JS -->
    <script src="assets/js/vendor.js"></script>

    <!-- Main JS -->
    <script src="assets/js/main.js"></script>
    {% endblock content %}

</body>