config/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls', namespace='home')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
] + debug_toolbar_urls()

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('product/<int:pk>/', views.ProductDetail.as_view(), name='product'),
    path('comment/<int:pk>/', views.CommentCreateView.as_view(), name='comment'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('add/<int:product_id>/', views.AddToCartView.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', views.RemoveFromCartView.as_view(), name='cart_remove'),
    path('clear/', views.ClearCartView.as_view(), name='cart_clear')
]

templates/inc/_footer.html
{% load static %}

       <footer class="footer">
            <div class="footer-top bg-color ptb--50" data-bg-color="#f6f6f6">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-9 text-center">
                            <div class="footer-widget mb--50">
                                <div class="textwidget">
                                    <img src="{% static 'img/logo/logo-white.png' %}" alt="Logo">
                                </div>
                            </div>
                            <div class="footer-widget mb--50 pb--1">
                                <ul class="footer-menu">
                                    <li><a href="">درباره ما</a></li>
                                    <li><a href="">قوانین و مقررات</a></li>
                                    <li><a href="">تماس با ما</a></li>
                                </ul>
                            </div>
                            <div class="footer-widget">
                                Codingyar.com © | all rights reserved
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

templates/inc/_header.html
{% load static %}
<header class="header">
    <div class="header-inner fixed-header">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-9 col-lg-8 col-5 col-xs-0 col-none col-sm-block p-0">
                    <nav class="main-navigation">
                        <div class="site-branding" style="margin-right: 30px;">
                            <a href="index.html" class="logo">
                                <figure class="logo--normal d-none d-sm-block">
                                    <img class="px-5" src="{% static 'img/logo/logo-white.png' %}" style="max-height: 50px; margin-bottom: -15px;" alt="Logo">
                                </figure>
                            </a>
                        </div>
                        <div class="mainmenu-nav d-none d-lg-block w-100 pr-3">
                            <ul class="mainmenu d-lg-flex jusity-content-end jusity-content-lg-start pt-4">
                                <li class="mainmenu__item menu-item-has-children active">
                                    <a href="{% url "home:home" %}" class="mainmenu__link">
                                        <span class="mm-text">خانه</span>
                                    </a>
                                </li>
                                <li class="mainmenu__item menu-item-has-children">
                                    <a href="Blog.html" class="mainmenu__link">
                                        <span class="mm-text">وبلاگ</span>
                                    </a>
                                </li>
                                <li class="mainmenu__item menu-item-has-children">
                                    <a href="#" class="mainmenu__link">
                                        <span class="mm-text">صفحات</span>
                                    </a>
                                 </li>
                                <li class="mainmenu__item">
                                    <a href="contact-us.html" class="mainmenu__link">
                                        <span class="mm-text">تماس با ما</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
                <div class="col-xl-3 col-lg-4 col-sm-7 col-12 p-0">
                    <ul class="header-toolbar">
                        <li class="header-toolbar__item">
                            <a href="wishlist.html" class="header-toolbar__btn mx-4">
                                <i class="flaticon flaticon-like"></i>
                            </a>
                        </li>
                        <li class="header-toolbar__item mini-cart-item">
                            <a href="#miniCart" class="header-toolbar__btn toolbar-btn mini-cart-btn">
                                <i class="flaticon flaticon-shopping-cart"></i>
                                <sup class="mini-cart-count">{{ cart|length }}</sup>
                            </a>
                        </li>
                        <li class="header-toolbar__item user-info">
                            <a href="my-account.html" class="header-toolbar__btn">
                                <i class="flaticon flaticon-user"></i>
                            </a>
                            <ul class="user-info-menu">
                                {% if user.is_authenticated %}
                                <li>
                                    <a class="text-right" href="{% url "account_logout" %}">خروج</a>
                                </li>
                                {% else %}
                                <li>
                                    <a class="text-right" href="{% url "account_login" %}">ورود</a>
                                </li>
                                <li>
                                    <a class="text-right" href="{% url "account_signup" %}">ثبت نام</a>
                                </li>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="header-toolbar__item">
                            <a href="#searchForm" class="header-toolbar__btn toolbar-btn">
                                <i class="flaticon flaticon-search"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="mobile-menu"></div>
                </div>
            </div>
        </div>
    </div>
</header>

templates/inc/_messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="alert alert-{{ message.tags }}" style="text-align:center"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/inc/_minicart.html
{% load humanize %}
{% load persian_numbers %}
<aside class="mini-cart" id="miniCart">
    <div class="mini-cart-wrapper">
        <a href="" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
        <div class="mini-cart-inner">
            <h3 class="mini-cart__heading mb--40 mb-lg--30 text-right">سبد خرید</h3>
            <div class="mini-cart__content">
                <ul class="mini-cart__list text-right">
                    {% for item in cart %}
                    <li class="mini-cart__product d-flex justify-content-between">
                        <div class="mini-cart__product__image">
                            <a href="#">
                                <img src="assets/img/products/prod-1-100x100.jpg" alt="products">
                            </a>
                        </div>
                        <div class="mini-cart__product__content pt-2">
                            <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                <a href="#"> {{ item.product_obj.title }} </a>
                                <a href="#" class="">
                                    &#10060;
                                </a>
                            </span>
                            <span class="mini-cart__product__quantity">
                                <span>{{ item.product_obj.price|intcomma|translate_number }}</span> &#215; <span>{{ item.quantity }}</span>
                            </span>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
                <div class="mini-cart__total">
                    <span>جمع کل</span>
                    <span class="ammount">{{ cart.get_total_price|intcomma|translate_number }}</span>
                </div>
                <div class="mini-cart__buttons">
                    <a href="{% url "shop:cart" %}" class="btn btn-fullwidth btn-bg-sand mb--20">مشاهده سبد خرید</a>
                    <a href="checkout.html" class="btn btn-fullwidth btn-bg-sand">پرداخت</a>
                </div>
            </div>
        </div>
    </div>
</aside>